version: 2.1

orbs:
  jira: circleci/jira@1.3.1

#==============================================================================
# Executors
#==============================================================================
executors:
  node_19:
    docker:
      - image: node:19.8.1
        auth:
          username: $MY_CIRCLECI_DOCKERHUB_USERNAME
          password: $MY_CIRCLECI_DOCKERHUB_PASSWORD
  node_18:
    docker:
      - image: node:18.15.0
        auth:
          username: $MY_CIRCLECI_DOCKERHUB_USERNAME
          password: $MY_CIRCLECI_DOCKERHUB_PASSWORD
  node_16:
    docker:
      - image: node:16.20.0
        auth:
          username: $MY_CIRCLECI_DOCKERHUB_USERNAME
          password: $MY_CIRCLECI_DOCKERHUB_PASSWORD

#==============================================================================
# Contexts
#==============================================================================
project_context: &project_context
  context:
    - generator-utils

#==============================================================================
# Filters
#==============================================================================
no_tag_filter: &no_tag_filter
  filters:
    branches:
      ignore: master
    tags:
      ignore: /.*/

#==============================================================================
# Commands
#==============================================================================
commands:
  test:
    steps:
      - run: |
          npm install
          npm test

#==============================================================================
# Jobs
#==============================================================================
jobs:
  test-16:
    executor: node_16
    steps:
      - checkout
      - test
  test-18:
    executor: node_18
    steps:
      - checkout
      - test
  test-19:
    executor: node_19
    steps:
      - checkout
      - test

#==============================================================================
# Workflows
#==============================================================================
workflows:
  #
  # General purpose pipeline to execute tests, no matter the source branches
  # It voluntary exclude tags to not have a double work with the automatic
  # release process (that also include testing))
  #
  "Test only pipeline":
    jobs:
      - test-16:
          <<: *project_context
          <<: *no_tag_filter
          post-steps:
            - jira/notify:
                job_type: build
      - test-18:
          <<: *project_context
          <<: *no_tag_filter
          post-steps:
            - jira/notify:
                job_type: build
