name: Pull request checks

on:
  pull_request:
    types: [opened, synchronized]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          node --version
          npm clean-install

      - name: Run tests
        run: |
          node --version
          npm run test

  coverage:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ success() }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          node --version
          npm clean-install

      - name: Run coverage
        run: |
          node --version
          npm run coverage

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
