name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          node --version
          npm install

      - name: Run tests
        run: |
          node --version
          npm run test

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]
