name: Prepare future release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  mutation-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use node 18
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install dependencies
        run: |
          node --version
          npm clean-install

      - name: Run mutation
        run: |
          node --version
          npm run mutation
